language: node_js
node_js:
  - 8.6.0 # latest
  - 6.11.3 # lts

script: "yarn && yarn test && yarn link && cd /tmp && yarn global add yo && $(yarn global bin)/yo pkgbuild test --yes --with-chroot --with-docker && cd test && make docker"
